#!/usr/bin/env python3
"""compute-fid.py — deterministic finding-id hashing (CLI + importable module).

Replaces the old free-text-based algorithm (hash of `file + LLM-generated issue summary
sentence`) with structured, deterministic inputs: a fixed-enum `category` (the sub-agent
chooses from a small closed vocabulary, not open prose) and the literal source code at the
finding's resolved location (read directly from the file on disk via extract-snippet.py, not
reported by the LLM). The old algorithm broke silently under re-review: the issue sentence is
regenerated by an LLM sub-agent on every run, so if a re-review's finder phrased the same bug
even slightly differently, the hash changed and reconcile.py reposted a duplicate instead of
recognizing the carried-over finding. This version doesn't have that failure mode: unchanged
code keeps the same fid even if it shifts line numbers; changed/fixed code naturally gets a
new identity.

fid = first 12 hex chars of sha1(lowercased path + "|" + category + "|" + normalized snippet)
Normalization (both path and snippet): lowercase, keep [a-z0-9 ], collapse whitespace, trim.
category is normalized to lowercase with only [a-z0-9-] kept, and must be one of
VALID_CATEGORIES — a closed vocabulary, not free text, so it can't introduce run-to-run drift.

reconcile.py imports this module's `compute_fid`/`fids_for_file` to re-verify a prior
finding's exact flagged line still exists at HEAD before ever bucketing it as "fixed" — see
that file's docstring. This filename's hyphen means a plain `import compute-fid` doesn't
parse, so reconcile.py loads it the same way scripts/tests/run.sh already loads this file
and reconcile.py itself: `importlib.util.spec_from_file_location`. That's an in-process
module load, not a subprocess — no shelling out, same as a normal import.

Note on comments already posted under the old algorithm: prior open findings marked
`pr-reviewer:v1` in their comment carry a fid computed by the retired formula above. This
script never recomputes those — reconcile.py matches prior vs. current findings by simple
string equality against whatever fid is already embedded in the old comment/thread, so an old
`v1` finding just won't match a freshly computed fid here and will be re-flagged as `new` on
its first re-review after this ships (a one-time, accepted side effect — see docs/). The
retired v1 formula itself is preserved in git history / the plugin's CHANGELOG, not in this
file, since nothing calls it anymore.

Usage:
    compute-fid.py <file> <category> <snippet>
    compute-fid.py --batch < findings.jsonl   # each line: {"file": ..., "category": ..., "snippet": ...}
                                                # prints back each line with "fid" added
"""
import sys
import re
import hashlib
import json

VALID_CATEGORIES = frozenset({
    "correctness",
    "security",
    "performance",
    "test-coverage",
    "maintainability",
})


def normalize_category(category: str) -> str:
    normalized = re.sub(r"[^a-z0-9-]", "", category.strip().lower())
    if normalized not in VALID_CATEGORIES:
        valid = ", ".join(sorted(VALID_CATEGORIES))
        raise ValueError(f"invalid category '{category}' (normalized '{normalized}') — must be one of: {valid}")
    return normalized


def normalize_snippet(snippet: str) -> str:
    text = re.sub(r"[^a-z0-9 ]", " ", snippet.lower())
    return re.sub(r"\s+", " ", text).strip()


def compute_fid(path: str, category: str, snippet: str) -> str:
    path = path.strip().lower()
    category = normalize_category(category)
    snippet = normalize_snippet(snippet)
    return hashlib.sha1(f"{path}|{category}|{snippet}".encode()).hexdigest()[:12]


def fids_for_file(path: str, category: "str | None" = None) -> set:
    """Return the set of fids obtainable from every line currently on disk at `path`,
    one fid per (line, category) pair. Used by reconcile.py to check whether a prior
    finding's exact flagged line still exists at HEAD — the same literal-line-plus-category
    inputs extract-snippet.py/compute_fid used to mint it originally, just recomputed in
    bulk instead of one line at a time.

    `category` narrows to a single category (when the prior finding's marker recorded one);
    `None` tries every VALID_CATEGORIES entry per line, for pre-category markers where we
    only know the fid, not what category minted it.
    """
    try:
        with open(path, "r", errors="replace") as f:
            lines = f.readlines()
    except OSError:
        return set()

    categories = [category] if category else sorted(VALID_CATEGORIES)
    fids = set()
    for line in lines:
        snippet = line.rstrip("\n")
        for cat in categories:
            try:
                fids.add(compute_fid(path, cat, snippet))
            except ValueError:
                continue
    return fids


def main():
    if len(sys.argv) == 2 and sys.argv[1] == "--batch":
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            obj = json.loads(line)
            obj["fid"] = compute_fid(obj["file"], obj["category"], obj["snippet"])
            print(json.dumps(obj))
        return

    if len(sys.argv) != 4:
        print("usage: compute-fid.py <file> <category> <snippet>", file=sys.stderr)
        print("       compute-fid.py --batch < findings.jsonl", file=sys.stderr)
        sys.exit(2)

    print(compute_fid(sys.argv[1], sys.argv[2], sys.argv[3]))


if __name__ == "__main__":
    main()
